//
// Created by Devon DaPuzzo on 12/3/20.
//

import Foundation

import XCTest
@testable import swift_2020

class TobogganMapTest: XCTestCase {

    func test_shouldLetMeKnowIllHitATreeOnMyFirstMove() {
        let map = TobogganMap.from(mapText: """
                                            ...........
                                            ...#.......
                                            ...........
                                            ...........
                                            ...........
                                            ...........
                                            ...........
                                            ...........
                                            ...........
                                            ...........
                                            ...........
                                            """, slope: (1, 3))

        let didHitTree = map.didHit(onMove: 1)

        XCTAssertEqual(didHitTree, true)
    }

    func test_shouldLetMeKnowIWontHitATreeOnMyFirstMove() {
        let map = TobogganMap.from(mapText: """
                                            ...........
                                            ...........
                                            ...........
                                            ...........
                                            ...........
                                            ...........
                                            ...........
                                            ...........
                                            ...........
                                            ...........
                                            ...........
                                            """, slope: (1, 3))

        let didHitTree = map.didHit(onMove: 1)

        XCTAssertEqual(didHitTree, false)
    }

    func test_shouldLetMeKnowIllHItATreeOnMySecondMOve() {
        let map = TobogganMap.from(mapText: """
                                            ...........
                                            ...........
                                            ......#....
                                            ...........
                                            ...........
                                            ...........
                                            ...........
                                            ...........
                                            ...........
                                            ...........
                                            ...........
                                            """, slope: (1, 3))

        let didHitTree = map.didHit(onMove: 2)

        XCTAssertEqual(didHitTree, true)
    }

    func test_shouldLetMeKnowWhenIGoOffTheMap() {
        let map = TobogganMap.from(mapText: """
                                            ...........
                                            ...........
                                            ...........
                                            ...........
                                            .#.........
                                            ...........
                                            ...........
                                            ...........
                                            ...........
                                            ...........
                                            ...........
                                            """, slope: (1, 3))

        let didHitTree = map.didHit(onMove: 4)

        XCTAssertEqual(didHitTree, true)
    }

    func test_shouldReturnNullWhenMapsDone() {
        let map = TobogganMap.from(mapText: """
                                            ...........
                                            ...........
                                            ...........
                                            ...........
                                            .#.........
                                            ...........
                                            ...........
                                            ...........
                                            ...........
                                            ...........
                                            ...........
                                            """, slope: (1, 3))

        let didHitTree = map.didHit(onMove: 11)

        XCTAssertNil(didHitTree)
    }

    func test_tellsMeHowManyTreesIHit() {
        let map = TobogganMap.from(mapText: """
                                            ...........
                                            ...#.......
                                            ...........
                                            ...........
                                            .#.........
                                            ...........
                                            ...........
                                            ...........
                                            ...........
                                            ...........
                                            ...........
                                            """, slope: (1, 3))

        let didHitTree = map.numberOfTreesHit()

        XCTAssertEqual(didHitTree, 2)
    }

}
